// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn5Uo-Are1DcMazhNxACIy95rvDLs_t9w',
    appId: '1:208868745154:web:337473b88e78ac435a405b',
    messagingSenderId: '208868745154',
    projectId: 'cashapp-1b9cd',
    authDomain: 'cashapp-1b9cd.firebaseapp.com',
    storageBucket: 'cashapp-1b9cd.appspot.com',
    measurementId: 'G-EVS4J2FBDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP1If_LCD-l1Q15cV8o_QjDtHqyIJjoII',
    appId: '1:208868745154:android:3420c709b178044c5a405b',
    messagingSenderId: '208868745154',
    projectId: 'cashapp-1b9cd',
    storageBucket: 'cashapp-1b9cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_4yC4ueqna0UMIyHeogkNDl8PsUmxTQQ',
    appId: '1:208868745154:ios:824247f0264cad6a5a405b',
    messagingSenderId: '208868745154',
    projectId: 'cashapp-1b9cd',
    storageBucket: 'cashapp-1b9cd.appspot.com',
    iosClientId: '208868745154-oqan69uc4nl1qelein95opjk6vrl6fdb.apps.googleusercontent.com',
    iosBundleId: 'com.example.earningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_4yC4ueqna0UMIyHeogkNDl8PsUmxTQQ',
    appId: '1:208868745154:ios:824247f0264cad6a5a405b',
    messagingSenderId: '208868745154',
    projectId: 'cashapp-1b9cd',
    storageBucket: 'cashapp-1b9cd.appspot.com',
    iosClientId: '208868745154-oqan69uc4nl1qelein95opjk6vrl6fdb.apps.googleusercontent.com',
    iosBundleId: 'com.example.earningApp',
  );
}
